[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/", "@solmate/=lib/solmate/src/", '@openzeppelin=lib/openzeppelin-contracts/', "@uniswap/=lib/v3-core", "@uniswap/=lib/v3-periphery"]
ffi = true


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
